export interface IUnderwriting {
    SSN:number,
    application_id:number,
 underwriting_id:number,
underwriter_names:string,
underwriting_status:string,
description:string,
date: Date,
ruleset_Version: number,
underwriting_score: number,
documents:string,
business_details:string,
business_type:string,
business_category:string,
business_name:string,
business_acc:number,
tax_id:number,
business_address:string,
underwriter_Channel: string
}